Diego Pablo Elias Cifuentes

```{r}
library(tidyverse)
library(dplyr)

yearly <- read_csv('deaths_handwashing.csv')
yearly
```

```{r}
yearly <- yearly %>%
  mutate(proportion_deaths=deaths/births)

yearly
```

```{r}
ggplot(yearly, aes(x = year, y = proportion_deaths, colour = clinic))+
  geom_line() +
  geom_point(size=2, shape=21, fill="white")+
  ggtitle("Proportion deaths per year")+
  labs(x="Year", y= "Proportion of deaths")
```

```{r}
monthly <- read_csv('deaths_clinic_1.csv')
monthly


monthly <- monthly %>%
  mutate(proportion_deaths = deaths/births)

head(monthly)
```

```{r}
proportion_deaths_per_day <- monthly %>%
  select(date, proportion_deaths)

ggplot(proportion_deaths_per_day, aes(x= date, y=proportion_deaths))+
  geom_line() +
  #geom_point( size=1, shape=21, fill="blue")+
  ggtitle("Proportion deaths per dayin clinic 1")+
  labs(x="Year", y= "Proportion of deaths")
 
```
```{r}
death_by_year <- monthly %>%
  mutate(date = as.Date(date), year = as.numeric(format(date,'%Y')), 
         month = as.numeric(format(date,'%m')))%>%
  group_by(year)%>%
  summarize(deaths_per_month = mean(deaths))%>%
  print(death_by_year)

ggplot(death_by_year, aes(x=year, y = deaths_per_month, fill = -deaths_per_month)) +
  geom_col()
```
6.

```{r}
monthly <- monthly %>%
  mutate(handwashing_started = monthly$date>="1847-01-01")%>%
  print(monthly)


ggplot(monthly, aes(x= date, y=proportion_deaths, color=handwashing_started))+
  geom_line() +
  #geom_point( size=1, shape=21, fill="blue")+
  ggtitle("Proportion deaths per dayin clinic 1")+
  labs(x="Year", y= "Proportion of deaths")


```
7.
```{r}
month_summary <- monthly %>%
  group_by(handwashing_started)%>%
  summarise(mean_proportion_deaths = mean(proportion_deaths))%>%
  print(month_summary)

```

8. 

```{r}

```























